vich_uploader:
    db_driver: orm

    mappings:
        member_image:
            uri_prefix: /uploads/members
            upload_destination: '%kernel.project_dir%/public/uploads/members'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
